### ISSUE TITLE
3D Lidar and 3D mapping

### ISSUE THREAD

**Issue by kylefjl** [wh200720041/warehouse_simulation_toolkit#2]
Sorry to disturb you, when I run your project, I don't  known how to  3D mapping

**Comment by wh200720041** [comment]
The gmapping  build 2d map only, if you would like to get 3D mapping, you can run [floam](https://github.com/wh200720041/floam) at the same time to get 3D map

**Comment by kylefjl** [comment]
thank you very much, I will try the floam
